# User Specified
run_name: philharmonic_demo
sequence_path: data/protein_seqs.fasta
go_filter_path: assets/go_filter.txt
work_dir: results
use_llm: false

# GFF Details
gff:
  path: data/pdam_annotation.gff3
  feature_type: "CDS"
  attribute_key: "protein_id"
  id_preface: ""

# Taxonomy
taxonomy:
  species: "Pocillopora damicornis"
  genus: "Pocillopora"
  family: "Pocilloporidae"
  order: "Scleractinia"
  class: "Hexacorallia"
  phylum: "Cnidaria"
  domain: "Eukaryota"

############################################

# General Parameters
seed: 42

# hmmscan Parameters
hmmscan:
  path: hmmscan
  threads: 32

# D-SCRIPT Parameters
dscript:
  path: dscript
  n_pairs: -1
  model: samsl/dscript_human_v1
  device: 0

# DSD Parameters
dsd:
  path: fastdsd
  t: 0.5
  confidence: true

# Clustering Parameters
clustering:
  init_k: 500
  min_cluster_size: 3
  cluster_divisor: 20
  sparsity_thresh: 1e-5

# ReCIPE Parameters
recipe:
  lr: 0.1
  cthresh: 0.75
  max_proteins: 20
  metric: degree

# LLM Naming Parameters
llm:
  model: gpt-4o
